-- AlterTable
ALTER TABLE "attendances" ALTER COLUMN "lat_in" SET DATA TYPE DECIMAL(12,8),
ALTER COLUMN "long_in" SET DATA TYPE DECIMAL(12,8),
ALTER COLUMN "lat_out" SET DATA TYPE DECIMAL(12,8),
ALTER COLUMN "long_out" SET DATA TYPE DECIMAL(12,8);
